Use GitHub CI service containers for CLI test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,16 +66,27 @@ jobs:
           github-token: ${{ secrets.github_token }}
           parallel-finished: true
 
-  cli:
+  testcli:
     needs: test
     runs-on: ubuntu-latest
+    env:
+      FUSEKI_USERNAME: admin
+      FUSEKI_PASSWORD: pw
+      JENA_DATASET: mydataset
+    services:
+      jenafuseki:
+        image: stain/jena-fuseki:4.8.0
+        env:
+          FUSEKI_DATASET_1: ${{ env.JENA_DATASET }}
+          ADMIN_PASSWORD: ${{ env.FUSEKI_PASSWORD }}
+        ports:
+          - 4000:3030
     steps:
       - uses: actions/setup-node@v4
         with:
           node-version: 20.x
       - run: git config --global core.autocrlf input
       - uses: actions/checkout@v4
-      - run: .github/workflows/start-docker.sh
       - uses: actions/cache@v4
         with:
           path: '**/node_modules'
@@ -83,8 +94,20 @@ jobs:
       - run: corepack enable
       - run: yarn install --ignore-engines --frozen-lockfile
       - run: yarn build
-      - run: .github/workflows/test-docker.sh
-      - run: .github/workflows/stop-docker.sh
+      - name: insert data
+        run: |
+          node bin/fetch-sparql-endpoint.js http://localhost:4000/${{ env.JENA_DATASET }}/update \
+            --query 'insert data { <ex:s> <ex:p> <ex:o> }' \
+            --username ${{ env.FUSEKI_USERNAME }} \
+            --password ${{ env.FUSEKI_PASSWORD }} \
+          | grep 'OK' &> /dev/null && echo "OK" || (echo "Update failed" && exit 1)
+      - name: test data existence
+        run: |
+          node bin/fetch-sparql-endpoint.js http://localhost:4000/${{ env.JENA_DATASET }}/sparql \
+            --query 'select * where { ?s ?p ?o }' \
+            --username ${{ env.FUSEKI_USERNAME }} \
+            --password ${{ env.FUSEKI_PASSWORD }} \
+          | grep '{"s":"ex:s","p":"ex:p","o":"ex:o"}' &> /dev/null && echo "OK" || (echo "Query failed" && exit 1)
 
   webpack:
     needs: test
