Run CLI test for all tested Node versions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,6 +36,19 @@ jobs:
           - 16.x
           - 18.x
           - 20.x
+    env:
+      FUSEKI_USERNAME: admin
+      FUSEKI_PASSWORD: pw
+      JENA_DATASET: mydataset
+      CLI_TIMEOUT: 5
+    services:
+      jenafuseki:
+        image: stain/jena-fuseki:4.8.0
+        env:
+          FUSEKI_DATASET_1: ${{ env.JENA_DATASET }}
+          ADMIN_PASSWORD: ${{ env.FUSEKI_PASSWORD }}
+        ports:
+          - 4000:3030
     steps:
       - uses: actions/setup-node@v4
         with:
@@ -55,6 +68,24 @@ jobs:
           github-token: ${{ secrets.github_token }}
           flag-name: run-${{ matrix.node-version }}
           parallel: true
+      - name: insert data using the cli
+        run: |
+          node bin/fetch-sparql-endpoint.js \
+            --endpoint http://localhost:4000/${{ env.JENA_DATASET }}/update \
+            --query 'insert data { <ex:s> <ex:p> <ex:o> }' \
+            --username ${{ env.FUSEKI_USERNAME }} \
+            --password ${{ env.FUSEKI_PASSWORD }} \
+            --timeout ${{ env.CLI_TIMEOUT }} \
+          | grep 'OK' &> /dev/null && echo "OK" || (echo "Update failed" && exit 1)
+      - name: test data existence using the cli
+        run: |
+          node bin/fetch-sparql-endpoint.js \
+            --endpoint http://localhost:4000/${{ env.JENA_DATASET }}/sparql \
+            --query 'select * where { ?s ?p ?o }' \
+            --username ${{ env.FUSEKI_USERNAME }} \
+            --password ${{ env.FUSEKI_PASSWORD }} \
+            --timeout ${{ env.CLI_TIMEOUT }} \
+          | grep '{"s":"ex:s","p":"ex:p","o":"ex:o"}' &> /dev/null && echo "OK" || (echo "Query failed" && exit 1)
 
   coveralls:
     needs: test
@@ -65,53 +96,6 @@ jobs:
         with:
           github-token: ${{ secrets.github_token }}
           parallel-finished: true
-
-  testcli:
-    needs: test
-    runs-on: ubuntu-latest
-    env:
-      FUSEKI_USERNAME: admin
-      FUSEKI_PASSWORD: pw
-      JENA_DATASET: mydataset
-    services:
-      jenafuseki:
-        image: stain/jena-fuseki:4.8.0
-        env:
-          FUSEKI_DATASET_1: ${{ env.JENA_DATASET }}
-          ADMIN_PASSWORD: ${{ env.FUSEKI_PASSWORD }}
-        ports:
-          - 4000:3030
-    steps:
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-      - run: git config --global core.autocrlf input
-      - uses: actions/checkout@v4
-      - uses: actions/cache@v4
-        with:
-          path: '**/node_modules'
-          key: ${{ runner.os }}-docker-modules-${{ hashFiles('**/yarn.lock') }}
-      - run: corepack enable
-      - run: yarn install --ignore-engines --frozen-lockfile
-      - run: yarn build
-      - name: insert data
-        run: |
-          node bin/fetch-sparql-endpoint.js \
-            --endpoint http://localhost:4000/${{ env.JENA_DATASET }}/update \
-            --query 'insert data { <ex:s> <ex:p> <ex:o> }' \
-            --username ${{ env.FUSEKI_USERNAME }} \
-            --password ${{ env.FUSEKI_PASSWORD }} \
-            --timeout 5 \
-          | grep 'OK' &> /dev/null && echo "OK" || (echo "Update failed" && exit 1)
-      - name: test data existence
-        run: |
-          node bin/fetch-sparql-endpoint.js \
-            --endpoint http://localhost:4000/${{ env.JENA_DATASET }}/sparql \
-            --query 'select * where { ?s ?p ?o }' \
-            --username ${{ env.FUSEKI_USERNAME }} \
-            --password ${{ env.FUSEKI_PASSWORD }} \
-            --timeout 5 \
-          | grep '{"s":"ex:s","p":"ex:p","o":"ex:o"}' &> /dev/null && echo "OK" || (echo "Query failed" && exit 1)
 
   webpack:
     needs: test
